language: generic

services: 
  - docker

branches:
  only:
  - kubernetes

before_install:
  - docker build -t mmicalt/multicontainer_api_getter -f./api_getter/Dockerfile ./api_getter
  - docker build -t mmicalt/multicontainer_api_setter -f./api_setter/Dockerfile ./api_setter
  - docker build -t mmicalt/multicontainer_client -f./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmicalt/multicontainer_api_getter npm run test
  - docker run -e CI=true mmicalt/multicontainer_api_setter npm run test
  - docker run -e CI=true mmicalt/multicontainer_client npm run test

after_success:
  - docker build -t mmicalt/multicontainer_api_getter -f./api_getter/Dockerfile ./api_getter
  - docker build -t mmicalt/multicontainer_api_setter -f./api_setter/Dockerfile ./api_setter
  - docker build -t mmicalt/multicontainer_api_worker -f./api_worker/Dockerfile ./api_worker
  - docker build -t mmicalt/multicontainer_client -f./client/Dockerfile ./client

  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

  - docker push mmicalt/multicontainer_api_getter
  - docker push mmicalt/multicontainer_api_setter
  - docker push mmicalt/multicontainer_api_worker
