language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mmicalt/multicontainer/server-test -f ./server/Dockerfile ./server
  - docker build -t mmicalt/multicontainer/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmicalt/multicontainer/server-test npm run test
  - docker run -e CI=true mmicalt/multicontainer/client-test npm run test

after_success:
  - docker build -t mmicalt/multicontainer/client ./client
  - docker build -t mmicalt/multicontainer/server ./server
  - docker build -t mmicalt/multicontainer/worker ./worker
  - docker build -t mmicalt/multicontainer/worker ./worker
  - docker build -t mmicalt/multicontainer/nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmicalt/multicontainer/client
  - docker push mmicalt/multicontainer/server
  - docker push mmicalt/multicontainer/worker
  - docker push mmicalt/multicontainer/worker
  - docker push mmicalt/multicontainer/nginx


# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "multicontainerApp"
#   env: "MulticontainerApp-env"
#   bucket_name: ""
#   bucket_path: "multicontainerApp"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
