language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mmicalt/multicontainer_server-test -f ./server/Dockerfile ./server
  - docker build -t mmicalt/multicontainer_client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmicalt/multicontainer_server-test npm run test
  - docker run -e CI=true mmicalt/multicontainer_client-test npm run test

after_success:
  - docker build -t mmicalt/multicontainer_client ./client
  - docker build -t mmicalt/multicontainer_server ./server
  - docker build -t mmicalt/multicontainer_worker ./worker
  - docker build -t mmicalt/multicontainer_worker ./worker
  - docker build -t mmicalt/multicontainer_nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmicalt/multicontainer_client
  - docker push mmicalt/multicontainer_server
  - docker push mmicalt/multicontainer_worker
  - docker push mmicalt/multicontainer_worker
  - docker push mmicalt/multicontainer_nginx


# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "multicontainerApp"
#   env: "MulticontainerApp-env"
#   bucket_name: ""
#   bucket_path: "multicontainerApp"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
