apiVersion: apps/v1
kind: Deployment
metadata:
  name: getter-deployment
  labels:
    app: getter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: getter
  template:
    metadata:
      labels:
        app: getter
    spec:
      containers:
        - name: getter
          image: mmicalt/multicontainer_api_getter
          ports:
            - containerPort: 3001
          env:
            - name: API_GETTER_PORT
              valueFrom:
                secretKeyRef:
                  name: envs
                  key: API_GETTER_PORT
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: envs
                  key: PG_USER
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: envs
                  key: PG_PORT
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: envs
                  key: PG_DATABASE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: envs
                  key: PG_PASSWORD
