version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    env_file:
      - .env
    links:
      - redis:redis
      - postgres:postgres

  redis:
    image: "redis:alpine"
    env_file:
      - .env
  postgres:
    image: "postgres"
    env_file:
      - .env

